language: java
jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=IC-2019.1 GRAMMAR_KIT_VERSION=2019.1
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT GRAMMAR_KIT_VERSION=2019.1

script: xvfb-run gradle check verifyPlugin

after_success:
  - gradle jacocoTestReport coveralls

jobs:
  include:
    - stage: deploy
      if: branch IN (Testing, Staging, Stable) AND type = push
      env: IDEA_VERSION=IC-2019.1 GRAMMAR_KIT_VERSION=2019.1 JI_CHANNELS=$TRAVIS_BRANCH
      script: xvfb-run gradle check verifyPlugin publishPlugin
